config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'products/:id', to: 'home#show', as: :product
  devise_for :admins
  devise_for :users, path: '', controllers: { registrations: 'users/registrations' }, path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :orders, only: [:create]
  resources :categories do
    get 'products', on: :member
  end

  authenticated :user do
    get 'profile', to: 'users#show'
  end

  resource :user, only: [:show, :update]
  get '/pages/:slug', to: 'static_pages#show', as: :static_page
  resource :cart, only: [:show] do
    post 'add', on: :collection
    post 'update_quantity', on: :collection
    delete 'remove', on: :collection
  end
  get 'order_summary', to: 'orders#summary', as: 'order_summary'
  post 'orders/create', to: 'orders#create', as: 'orders_create'
  get 'orders', to: 'orders#index', as: 'index_orders'

  # namespace :admin do
  #   get 'dashboard/index'
  #   devise_for :admins, skip: :registrations
  #   root to: "products#index"
  #   resources :products
  #   resources :categories
  #   resources :users, only: [:index]
  #   resources :orders, only: [:index, :show, :destroy]
  # end
  resources :products, only: [:show]
  root 'home#index'
  get 'home/sale', to: 'home#sale'
  get 'home/new', to: 'home#new', as: 'home_new'
  get "up" => "rails/health#show", as: :rails_health_check
  get 'tax_rates/:province_id', to: 'taxes#rates', as: 'tax_rates'
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  def show
    @cart_items = session[:cart].map do |product_id, quantity|
      product = Product.find(product_id)
      { product: product, quantity: quantity }
    end
  rescue ActiveRecord::RecordNotFound

    session[:cart].delete(product_id)
    redirect_to cart_path, alert: "A product in your cart is no longer available."
  end

  def add
    product_id = params[:product_id].to_s
    quantity = params[:quantity].to_i
  
    # Initialize the cart session if it doesn't exist
    
    session[:cart] ||= {}
    session[:cart] = Hash(session[:cart])
    # Add the product to the cart or update its quantity
    if session[:cart].has_key?(product_id)
      session[:cart][product_id] += quantity
    else
      session[:cart][product_id] = quantity
    end
  
    # Redirect to the cart page with feedback to the user
    redirect_to cart_path, notice: "Added #{quantity} #{'unit'.pluralize(quantity)} of #{Product.find(product_id).name} to your cart."
  end
  


  def update_quantity
    product_id = params[:product_id]
    new_quantity = params[:quantity].to_i

    if new_quantity > 0
      session[:cart][product_id] = new_quantity
      flash[:notice] = "Cart updated successfully."
    else
      flash[:alert] = "Invalid quantity."
    end

    redirect_to cart_path
  end


  def remove
    session[:cart].delete(params[:product_id].to_s)
    redirect_to cart_path, notice: 'Product removed from cart successfully.'
  end

  private

  def initialize_cart
    session[:cart] ||= {}
  end
      

end

app/views/carts/show.html.erb
<%= render 'layouts/client_Nav' %>
<div class="container">
  <h1 class="my-4">Your Shopping Cart</h1>
  <% if session[:cart].present? %>
    <% total_price = 0 %>
    <% session[:cart].each do |product_id, quantity| %>
      <% product = Product.find(product_id) %>
      <% total_price += product.price * quantity %>
      <div class="row mb-3">
        <div class="col-md-8">
          <div class="d-flex justify-content-between align-items-center">
            <div>
              <h5><%= product.name %></h5>
              <%= form_with url: update_quantity_cart_path, method: :post, local: true do |form| %>
                <div class="d-flex align-items-center">
                  <%= form.label :quantity, "Quantity:", class: "mr-2" %>
                  <%= form.number_field :quantity, value: quantity, min: 1, class: 'form-control mr-2', style: 'width: 80px;' %>
                  <%= form.hidden_field :product_id, value: product_id %>
                  <%= form.submit "Update", class: "btn btn-primary btn-sm" %>
                </div>
              <% end %>
              <p>Unit Price: <%= number_to_currency(product.price) %></p>
              <p>Subtotal: <%= number_to_currency(product.price * quantity) %></p>
            </div>
            <div>
              <%= link_to 'View Product', product_path(product), class: 'btn btn-info btn-sm mr-2' %>
              <%= button_to 'Remove', remove_cart_path(product_id: product.id), method: :delete, class: 'btn btn-danger btn-sm' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="row">
      <div class="col-md-8">
        <div class="d-flex justify-content-between">
          <h4>Total Cart Value: <%= number_to_currency(total_price) %></h4>
          <%= link_to 'Place Order', order_summary_path, class: "btn btn-success" %>
        </div>
      </div>
    </div>
  <% else %>
    <p>Your cart is empty.</p>
  <% end %>
</div>