config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'products/:id', to: 'home#show', as: :product
  devise_for :admins
  devise_for :users, path: '', controllers: { registrations: 'users/registrations' }, path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :orders, only: [:create]
  resources :categories do
    get 'products', on: :member
  end

  authenticated :user do
    get 'profile', to: 'users#show'
  end

  resource :user, only: [:show, :update]
  get '/pages/:slug', to: 'static_pages#show', as: :static_page
  resource :cart, only: [:show] do
    post 'add', on: :collection
    post 'update_quantity', on: :collection
    delete 'remove', on: :collection
  end
  get 'order_summary', to: 'orders#summary', as: 'order_summary'
  post 'orders/create', to: 'orders#create', as: 'orders_create'
  get 'orders', to: 'orders#index', as: 'index_orders'

  # namespace :admin do
  #   get 'dashboard/index'
  #   devise_for :admins, skip: :registrations
  #   root to: "products#index"
  #   resources :products
  #   resources :categories
  #   resources :users, only: [:index]
  #   resources :orders, only: [:index, :show, :destroy]
  # end
  resources :products, only: [:show]
  root 'home#index'
  get 'home/sale', to: 'home#sale'
  get 'home/new', to: 'home#new', as: 'home_new'
  get "up" => "rails/health#show", as: :rails_health_check
  get 'tax_rates/:province_id', to: 'taxes#rates', as: 'tax_rates'
end

app/views/layouts/_client_Nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
  <%= link_to root_path, class: 'navbar-brand' do %>
  <%= image_tag('logo.png', alt: 'Logo', class:"logo") %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
      <li class="nav-item">
          <%= link_to "About", static_page_path(slug: 'About'), class: "nav-link" %> <!-- Updated About link -->
        </li>
        <li class="nav-item">
          <%= link_to "Contact", static_page_path(slug: 'Contact'), class: "nav-link" %> <!-- Updated Contact link -->
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to 'Recent Orders', index_orders_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'View Cart', cart_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Settings', profile_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-primary nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_products.html.erb
<div class="col-md-3 mb-4">
<div class="product-card">
  <div class="product-card-img">
    <% if product.image.attached? %>
      <%= image_tag(product.image, class: 'img-fluid') %>
    <% else %>
      <img src="https://via.placeholder.com/350x350" class="img-fluid" alt="Product Image">
    <% end %>
  </div>
  <div class="product-card-body">
    <h5 class="product-title"><%= product.name %></h5>
    <p class="product-description"><%= product.description %></p>
    <div class="product-price">Price: <%= number_to_currency(product.price) %></div>
  </div>
  <div class="product-card-footer text-center">
    <%= link_to 'Learn More', product_path(product), class: 'btn btn-outline-primary' %>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerse Project</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <style>
    .product-card {
  display: flex;
  flex-direction: column;
  background: white;
  border: 1px solid #e1e1e1;
  border-radius: 8px;
  overflow: hidden;
  transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.product-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

.product-card-img img {
  width: 100%;
  height: auto;
  border-bottom: 1px solid #e1e1e1;
}

.product-card-body {
  padding: 15px;
  flex-grow: 1;
}

.product-title {
  font-size: 1.25rem;
  margin-bottom: 0.5rem;
}

.product-description {
  font-size: 0.9rem;
  flex-grow: 1;
}

.product-price {
  font-weight: bold;
  margin-top: 0.5rem;
}

.product-card-footer {
  padding: 10px 15px;
  background: #f9f9f9;
}

.btn-outline-primary {
  border-color: #007bff;
  color: #007bff;
}

.btn-outline-primary:hover {
  background: #007bff;
  color: #fff;
}
.product-detail-card {
  display: flex;
  flex-direction: column;
  align-items: center;
  background: #fff;
  padding: 20px;
  border-radius: 8px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}

.product-image img {
  max-height: 400px;
  width: auto;
  border-radius: 8px;
  margin-bottom: 20px;
}

.product-content {
  text-align: center;
}

.product-title {
  font-size: 2.5rem;
  margin-bottom: 20px;
}

.product-description {
  font-size: 1rem;
  color: #666;
  margin-bottom: 20px;
}

.product-category, .product-ingredients, .product-price {
  font-size: 1.1rem;
  margin-bottom: 10px;
}

.btn-outline-secondary {
  font-weight: bold;
  border-width: 2px;
}

.category-card {
  background: #f7f7f7;
  padding: 20px;
  border-radius: 10px;
  text-align: center;
}

.category-link {
  display: block;
  padding: 20px;
  transition: background-color 0.3s ease;
}

.category-link:hover {
  background-color: #e7e7e7;
}

.category-title {
  font-size: 1.5rem;
  margin: 0;
}
.table {
  border-collapse: collapse;
  width: 100%;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  border-radius: 8px;
  overflow: hidden;
}

.table thead th {
  background-color: #f8f9fa;
  color: #495057;
  border-bottom: 2px solid #dee2e6;
  padding: 12px 15px;
}

.table tbody td {
  padding: 12px 15px;
  color: #495057;
  border-bottom: 1px solid #dee2e6;
}

.table tbody tr:last-child td {
  border-bottom: none;
}

.table-hover tbody tr:hover {
  background-color: #f1f3f5;
}

.btn-sm {
  padding: 0.25rem 0.5rem;
  font-size: 0.875rem;
  line-height: 1.5;
  border-radius: 0.2rem;
}

.img-fluid {
  max-width: 100%;
  height: auto;
}
.table-hover tbody tr:hover {
  background-color: #f5f5f7;
}

.table-bordered th, .table-bordered td {
  border: 1px solid #dee2e6;
}

.table th {
  width: 20%;
  background-color: #e9ecef;
  color: #495057;
}

.table td {
  background-color: #ffffff;
}

.card-body {
  overflow-x: auto; /* Ensures the table is responsive on smaller screens */
}


    </style>
  </head>
  <body>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  

   
    <%= yield %>
  </body>
</html>